when@dev:
  framework:
    cache:
      directory: '%kernel.cache_dir%/pools' # Only used with cache.adapter.filesystem

      # Unique name of your app: used to compute stable namespaces for cache keys.
      #prefix_seed: your_vendor_name/app_name

      # The "app" cache stores to the filesystem by default.
      # The data in this cache should persist between deploys.
      # Other options include:

      pools:
        product.cache:
          adapter: cache.adapter.filesystem
          tags: true


when@prod:
  framework:
    cache:
      # Unique name of your app: used to compute stable namespaces for cache keys.
      #prefix_seed: your_vendor_name/app_name

      # The "app" cache stores to the filesystem by default.
      # The data in this cache should persist between deploys.
      # Other options include:

      # default_redis_provider: snc_redis.default
      pools:
        product.cache:
          # Redis
          adapter: cache.adapter.redis
          tags: true
          default_lifetime: 1800
          provider: snc_redis.default
